repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # 使用最新版本
    hooks:
      - id: ruff-format       # 运行 Ruff 格式化
      - id: ruff             # 运行 Ruff 检查并自动修复
        args: [--fix]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: coverage
        name: coverage
        entry: bash -c 'python -m coverage run -m pytest && python -m coverage report --fail-under=100'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true